### ISSUE TITLE
Invulnerable power pylon (and other issues)

### ISSUE THREAD

**Issue by vi** [Smujb/yet-another-shattered-dungeon#7]
Seed: 3571132342641
Commit: e553e8ca0894c578f507afca8832a3c7798adfea (save file also started on this commit).

DM-300 battle stalled because of power pylon cannot be destroyed. The pylon shows in the list of enemies, but that icon cannot be clicked (nothing happens). Inspecting it shows zero health for some reason.

[Video](https://vi-server.org/pub/yasd_issue_7.webm)

Other issues:

* After the Tengu figth, cannot normally descend down to mines, only fall. After the fall, ascending leads to the shop floor above Tengu. Later, after returning with a Feather Fall, it descended and ascended normally.
* Sandals/Boots of Nature was't giving any additional seeds compared to normal seed drop rate unless I reordered armours, weapons and artifacts for boots to be on the third (intead of fifth) slot.

**Comment by Smujb** [comment]
Okay, I'll have to work on this. That last one tho, I doubt it's more than just bad luck, as items don't know the slot they are equipped in.

**Comment by vi** [comment]
The drop rate increase was rather drastic as soon as I reordered them (artifact was already upgraded to +7). If it's not the slot number, it may be some other issue. Charge counters was counting upwards even when it was on fifth slot.

I primary issue is resolved (and game can progress), I can reorder them back and measure.

**Comment by Smujb** [comment]
Fixing your save for the first one is going to be hard unfortunately. Try using wands if possible? Otherwise, game prevents you attacking smth with 0 HP. This is done to prevent double death (eg from Grim) and is likely impossible to change...

**Comment by vi** [comment]
Indeed, using the wand solved the stall. Next power pylon is also zero health. Descending to next floor worked like it should.

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/ff72daaa3b03125bcbbb614b9a9ea50ca89f8c6d and https://github.com/Smujb/yet-another-shattered-dungeon/commit/1f888df6fea35bf94a6a6b97f7bca64921baebca

As for the Tengu level bug I have been unable to reproduce it. Idk what was going on, I assume it was down to old save?

**Comment by vi** [comment]
No, the game started at commit e553e8ca0894c578f507afca8832a3c7798adfea.

But absense of the downstairs tile was transient: second time I returned to the Tengu floor it worked as designed.

**Comment by vi** [comment]
Encountered Dwarven Ghoul with similar properties.

**Comment by Smujb** [comment]
The Tengu bug mentioned here was caused by something probably fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/5351987ff3775d76720f6b2a3f7e89a95f9e1aa0 where I reworked depth switching system. Everything else is resolved (Ghouls by https://github.com/Smujb/yet-another-shattered-dungeon/commit/a76ee8a4b7ddb0cc0165c490fca9d888a17d6910 for example)
